### ISSUE TITLE
Automatically set store credit to paid

### ISSUE THREAD

**Issue by amdrew** [awesomemotive/affiliatewp-store-credit#1]
A customer has suggested that there's no need with store credit to have to click "mark as paid". Because it's just store credit, it should be automatically paid to the affiliate. Balls in your court.

**Comment by ramiabraham** [comment]
Another request for this (https://secure.helpscout.net/conversation/90074072/9208/) - seems like we just need to filter $ref_status and provide an option somewhere.

**Comment by wordmaid** [comment]
Here's another request, automatically set to Unpaid after X amount of days (e.g. 30): https://secure.helpscout.net/conversation/144119241/22464/?folderId=414056

**Comment by kellenmace** [comment]
In lieu of an official option for automatically marking new referrals as paid, here's a workaround I built that's based off of renegadesk's solution above. Mine does not require WooCommerce, though - just AffiliateWP.

https://gist.github.com/kellenmace/96518f9c5ca42bfecad7

After a new affiliate has been created, it waits 1 minute then makes sure the status of the last 50 referrals is set to paid. This assumes you have "Auto Register New Users" enabled in AffiliateWP settings. If you don't, you'll probably want to use WordPress' user_register hook instead of affwp_insert_affiliate on line 10.

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/664242529/90299?folderId=205524

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/667927060/0/?folderId=634609

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/718785436/95480?folderId=634609

**Comment by gspice** [comment]
Another request:
https://secure.helpscout.net/conversation/725029264/96150?folderId=1170842

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/767268984/99763?folderId=634609

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/770380415/99979?folderId=205524

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/771305305/100077/

**Comment by michaelbeil** [comment]
https://secure.helpscout.net/conversation/781046025/101094?folderId=205524

**Comment by forilinki** [comment]
Hello,

Is this resolved? I am trying to modify the code but it does not work for me. I would appreciate your help.

Thanks in advance,

**Comment by baowesome** [comment]
any update about this?

**Comment by baowesome** [comment]
> Something quick for this https://github.com/RenegadeEmpire/affiliatewp-store-credit-autopay/ that we're testing on our site at the moment. Any feedback is more than welcome!

its not working please help

**Comment by michaelbeil** [comment]
@baowesome this is _not_ a feature that has been implemented. The plugin you referenced above is a 3rd-party plugin. You will need to connect with the 3rd-party author about why it is not working for you.

**Comment by gspice** [comment]
Another user has requested this on this HS ticket:
https://secure.helpscout.net/conversation/932438954/128073/?folderId=1170842

>is it possible, everytime an affiliate's referrals buy something, to have the money earned by the affiliate to be automatically payout as Store Credit?

**Comment by gspice** [comment]
We need this! Another request: 
https://secure.helpscout.net/conversation/1067729003/144029?folderId=1170842

> Is there no option to make the payout automatic?
Requiring manual action by the administrators is very time consuming, it would be optimal to be automatic

**Comment by gspice** [comment]
Another request, makes sense to add:
https://secure.helpscout.net/conversation/1225037258/159962?folderId=1170842

>Is there a way to have the referrals set as PAID automatically?
I would like to avoid set them up every single time as it's just store
credit.

**Comment by tjackson1317** [comment]
> do I have to manually generate a payout each time?

https://secure.helpscout.net/conversation/1329261479/169617?folderId=205529

**Comment by tjackson1317** [comment]
> I do not find option, to auto-payout users with store credit. Still have to payout them manually, while an automation is needed. Please tell me, how to automate it.

https://secure.helpscout.net/conversation/1443878496/179157/

**Comment by tjackson1317** [comment]
> I wanted to request a feature for coupons. We need a feature which allow us to give our Partner a Coupon, but give them less commission if the coustomer pay with the coupon.
> 
> So for example the Partner has officially 20% Comission on his refferal link and a 20% off Coupon which is connected to his affiliate account. If a coustomer pays with his coupon that he wont recieve 20% Commision but only 10% for example.

https://secure.helpscout.net/conversation/1520606995/185438?folderId=205524
