### ISSUE TITLE
Add the ability for admins to reset an affiliate's store credit balance to zero

### ISSUE THREAD

**Issue by gspice** [awesomemotive/affiliatewp-store-credit#63]
We have received support requests asking to clear out an affiliate's store credit balance, to take them back to zero.  Currently the only way to do this is via a database change.  With the new changes happening on #10 , it would be great if a button or link can be added to the admin, edit affiliate screen next to the **Store Credit Balance** amount to reset them to a zero balance.

**Comment by amdrew** [comment]
@gspice After thinking about this I'm not sure if this is a good idea. Could you link me to the tickets in question? What were the use-cases?

Here's an example:

An affiliate has 2 paid referrals totalling $50 each, for a grand total of $100. They now have $100 in store credit. 

If we reset their store balance to `$0.00` (by simply updating the `affwp_wc_credit_balance` meta key) they now have  `$0.00` in store credit as expected. However, if the admin ever set those 2 referrals from `paid` to `unpaid`, the amount of each referral will be taken away from the affiliate's store credit. Since they had `$0.00`, `$100` would be taken away, leaving them with `-$100`. The site admin would have to remember to never touch the associated referrals (which is risky). 

Another way would be to set all the associated referrals to `unpaid`, thus reducing the affiliate's balance to $0.00. This also might not be a great idea.

I guess the question is, why allow the store credit balance to be reset?

**Comment by gspice** [comment]
@amdrew 

Here are a couple of tickets I was able to find:

https://secure.helpscout.net/conversation/507586574/74318/?folderId=205529
https://secure.helpscout.net/conversation/518749839/75567/?folderId=205529

That said, I'm not set on this reset happening, could just leave the issue open in case other use-cases materialize?

**Comment by gspice** [comment]
Here's another from today:
https://secure.helpscout.net/conversation/558505433/80096/?folderId=205529

**Comment by gspice** [comment]
Had another request for this today. Some affiliates use Store Credit and some do not. They paid out cash to the affiliates for their referrals by accident, and were looking for a way to lower the Store Credit balance to zero or else it would be like double-payment:
https://secure.helpscout.net/conversation/840756177/119231?folderId=1170842

**Comment by DrewAPicture** [comment]
Seems like something we should definitely do, if only to give the store owner some greater measure of control here.

Following up on @amdrew's great feedback above, particularly:
> I guess the question is, why allow the store credit balance to be reset?

In this particular use case, manual payment overrides online payment. Maybe that's kind of voiding the warranty, so to speak, but still a reasonably valid use case. Your point about what would happen if the referrals were later marked `unpaid` from `paid` would certainly have to be guarded against.

I could see either not allowing the status on those referrals to change, or more likely, put protections in place that allow a store owner to change the referral status without affecting the store credit balance, maybe in the form of something like a checkbox they'd have to check in the referral editing screen? I don't know, just tossing ideas around :-)

**Comment by gspice** [comment]
@DrewAPicture Your last comments directly apply (I think) to another issue I just entered #101

**Comment by gspice** [comment]
Another ticket asking how to reset an affiliate's store credit balance:
https://secure.helpscout.net/conversation/855444414/120832/?folderId=205529

>How do I reset the Store Credit Balance for an affiliate. They have requested the payment instead and I can't both pay them and let them to have credit in their account as well. The amount is pretty large: $15,585.65 and the field is grayed out on the affiliate's profile.

**Comment by gspice** [comment]
Another request asking how to remove store credit from an affiliate's balance:
https://secure.helpscout.net/conversation/906710679/125519/?folderId=205529

>How do I remove a store credit?
>A customer prepaid us and we thought we'd use an affiliate credit to manage this. Bad idea (on our part) as it messes with the local tax being charged and collected. So I removed the credit on the account but there is still a store credit showing for his affiliate account and at checkout. I may very well be missing something simple but please help me understand how I remove or delete is existing store credit.

**Comment by tjackson1317** [comment]
> Occasionally there is an error or need to edit the store credit balance for an affiliate. But we can not edit this balance through the Affiliate screen. We have to directly manipulate the user_meta table in the database.
> 
> Any chance we can get a version that allows us to modify the Affiliate Credit Balance?

https://secure.helpscout.net/conversation/1409599686/176200/

**Comment by tjackson1317** [comment]
> I have someone that we had an error on the store credit add on but now we can't adjust the store credit back to $0. Is there a way to override this?

https://secure.helpscout.net/conversation/1577236323/189937?folderId=205524

**Comment by tjackson1317** [comment]
Adjusting store credit (Subtracting an amount)

We have a need to adjust an affiliates store credit. In this case we need to subtract an amount, say $20. So they have a $200 store credit and we need to remove $20 to make it $180. Can we do this?

https://secure.helpscout.net/conversation/1624269442/193637/

**Comment by shaynesanderson** [comment]
Another request to be able to admins to adjust store credit. 

https://secure.helpscout.net/conversation/1698939171/1644530?folderId=5762581

**Comment by gspice** [comment]
I've added this feature request to the new site, along with the HS links from the new HS account

https://team.affiliatewp.com/feature-requests/add-the-ability-to-change-affiliates-store-credit-balance/
